### ISSUE TITLE
Expose ILoggingProvider

### ISSUE THREAD

**Issue by tylerhartwig** [BlazorExtensions/Logging#42]
I've been trying to add logging for my SignalR client, and after reading documentation found that you are supposed to do it by adding a logging provider.

This library hides it's `ILoggerProvider`, why?

I've added this class for SignalR logging via reflection for now, but is there harm in making this class public?

**Comment by attilah** [comment]
You'd like to see ```BrowserConsoleLoggerProvider``` exposed?

**Comment by tylerhartwig** [comment]
This is correct

**Comment by galvesribeiro** [comment]
Sorry but I don't understand why you need access to the concrete browser console implementation.

If you want to add it anywhere all you need to do is to get the `ILoggerProvider` interface. 

In all cases, if that was supposed to be used on Blazor.SignalR, that repo was archived since there is an official client.

I'm going to close this issue since there is nothing needed to be done.
